#!/usr/bin/env php
<?php

// If we're running from phar load the phar autoload file.
$pharPath = \Phar::running( true );
if ( $pharPath ) {
	$autoloaderPath = "$pharPath/vendor/autoload.php";
} else {
	if ( file_exists( __DIR__ . '/vendor/autoload.php' ) ) {
		$autoloaderPath = __DIR__ . '/vendor/autoload.php';
	} elseif ( file_exists( __DIR__ . '/../../autoload.php' ) ) {
		$autoloaderPath = __DIR__ . '/../../autoload.php';
	} else {
		die( "Could not find autoloader. Run 'composer install'." );
	}
}
$classLoader = require $autoloaderPath;

use Robo\Robo;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;
use Tribe\Sq1\SquareOne;

$input                 = new ArgvInput( $argv );
$output                = new ConsoleOutput();
$configurationFilename = __DIR__ . '/config/constants.yml';
$config                = Robo::createConfiguration( [ $configurationFilename ] );
$version               = trim( file_get_contents( __DIR__ . '/VERSION' ) );
$sq1                   = new SquareOne( $version, $config, $input, $output );
$status_code           = $sq1->run( $input, $output );
exit( $status_code );
