# The default services stack for the SquareOne framework
# See https://github.com/moderntribe/square-one

x-networks: &proxynetwork
  networks:
    - global_square1

x-internaldns: &internaldns
  dns: 172.20.10.250

x-nginx: &nginx
  image: nginx:stable-alpine
  working_dir: /application
  volumes:
    - appdata:/application/www:ro,nocopy,cached
    - ./nginx/fastcgi_params.conf:/etc/nginx/templates/fastcgi_params.template
    - ${SQ1_PROJECT_ROOT}/dev/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

x-memcached: &memcached
  image: ${SQ1_MEMCACHED_IMAGE:-memcached:alpine}

x-redis: &redis
  image: ${SQ1_REDIS_IMAGE:-redis:alpine}

x-chrome: &chrome
  image: 'selenium/standalone-chrome:3.141.59'
  volumes:
    - '/dev/shm:/dev/shm'
  ports:
    - 4444

x-php: &php
  image: ${SQ1_PHP_IMAGE:-moderntribe/squareone-php:74-2.1}
  working_dir: /application
  user: "${SQ1_UID:-1000}:${SQ1_GID:-1000}"
  volumes:
    - appdata:/application/www:cached
    - ${SQ1_PROJECT_ROOT}/dev/docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/zz-overrides.ini
    - ${SQ1_PROJECT_ROOT}/dev/docker/php/msmtp.conf:/etc/msmtprc:ro
    - ${SQ1_PROJECT_ROOT}/dev/docker/wp-cli.yml:/application/wp-cli.yml
    - ${SQ1_PROJECT_ROOT}/dev/docker/composer:/application/.composer
  external_links:
    - "tribe-mysql:mysql"
    - "tribe-mail:mail"
  environment:
    - COMPOSER_ALLOW_SUPERUSER=1
    - COMPOSER_MEMORY_LIMIT=-1
    - COMPOSER_PROCESS_TIMEOUT=0
    - COMPOSER_HOME=/application/.composer
    - PHP_IDE_CONFIG=serverName=${SQ1_HOSTNAME:-square1.tribe}
    - DOMAIN_CURRENT_SITE=${SQ1_HOSTNAME:-square1.tribe}
    - DB_NAME=tribe_${SQ1_DB_NAME}
    - DB_USER=root
    - DB_PASSWORD=password
    - DB_HOST=mysql
    - DB_TABLE_PREFIX=tribe_
    - WP_DEBUG_LOG='php://stderr'

x-elasticsearch: &elasticsearch
  image: ${SQ1_ES_IMAGE:-elasticsearch:6.5.3}
  ports:
    - "9200"
  environment:
    - cluster.name=square1
    - bootstrap.memory_lock=true
    - discovery.type=single-node
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 65536
      hard: 65536
  volumes:
    - ${SQ1_PROJECT_ROOT}/dev/docker/elasticsearch/data:/usr/share/elasticsearch/data:delegated

x-solr: &solr
  image: ${SQ1_SOLR_IMAGE:-solr:7}
  volumes:
    - appdata:/var/www:ro,nocopy,cached

services:

  memcached:
    <<: *memcached
    <<: *proxynetwork

  redis:
    <<: *redis
    <<: *proxynetwork

  php-fpm:
    <<: *php
    <<: *internaldns
    <<: *proxynetwork

  webserver:
    <<: *nginx
    <<: *proxynetwork
    environment:
      - FPM_CONTAINER=php-fpm:9000
      - VIRTUAL_HOST=${SQ1_HOSTNAME:-square1.tribe},*.${SQ1_HOSTNAME:-square1.tribe}

  elasticsearch:
    <<: *elasticsearch
    <<: *proxynetwork

  solr:
    <<: *proxynetwork
    <<: *solr

  ##################################################
  # Testing Containers
  ##################################################

  memcached-tests:
    <<: *memcached
    <<: *proxynetwork

  redis-tests:
    <<: *redis
    <<: *proxynetwork

  php-tests:
    <<: *php
    <<: *internaldns
    <<: *proxynetwork
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - COMPOSER_MEMORY_LIMIT=-1
      - COMPOSER_PROCESS_TIMEOUT=0
      - COMPOSER_HOME=/application/.composer
      - PAGER=more
      - PHP_IDE_CONFIG=serverName=${SQ1_HOSTNAME_TESTS:-square1test.tribe}
      - DOMAIN_CURRENT_SITE=${SQ1_HOSTNAME_TESTS:-square1test.tribe}
      - DB_NAME=tribe_${SQ1_DB_NAME}_acceptance
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_HOST=mysql
      - DB_TABLE_PREFIX=tribe_
      - WP_DEBUG_LOG='php://stderr'
      - TRIBE_GLOMAR=false
      - DISABLE_OBJECT_CACHE=true

  webserver-tests:
    <<: *nginx
    <<: *proxynetwork
    environment:
      - FPM_CONTAINER=php-tests:9000
      - VIRTUAL_HOST=${SQ1_HOSTNAME_TESTS:-square1test.tribe},*.${SQ1_HOSTNAME_TESTS:-square1test.tribe}

  chrome:
    <<: *chrome
    <<: *internaldns
    <<: *proxynetwork

  elasticsearch-tests:
    <<: *elasticsearch
    <<: *proxynetwork

  solr-tests:
    <<: *solr
    <<: *proxynetwork

networks:
  global_square1:
    external:
      name: ${SQ1_PROXY_NETWORK:-global_square1}
