# The default services stack for the SquareOne framework
# See https://github.com/moderntribe/square-one

version: "3.4"

x-networks: &proxynetwork
  networks:
    - proxy

x-internaldns: &internaldns
  dns: 172.20.10.250

x-nginx: &nginx
  image: nginx:stable-alpine
  working_dir: /application
  volumes:
    - appdata:/application/www:ro,nocopy,cached
    - ${SQ1_PROJECT_ROOT}/dev/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    - ${SQ1_PROJECT_ROOT}/dev/docker/nginx/fastcgi.conf:/etc/nginx/fastcgi_params

x-memcached: &memcached
  image: memcached:alpine

x-chrome: &chrome
  image: 'selenium/standalone-chrome:3.141.59'
  volumes:
    - '/dev/shm:/dev/shm'
  ports:
    - 4444

x-php: &php
  image: ${SQ1_PHP_IMAGE:-moderntribe/squareone-php:74-2.1}
  working_dir: /application
  user: "${SQ1_UID:-1000}:${SQ1_GID:-1000}"
  volumes:
    - appdata:/application/www:cached
    - ${SQ1_PROJECT_ROOT}/dev/docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/zz-overrides.ini
    - ${SQ1_PROJECT_ROOT}/dev/docker/php/msmtp.conf:/etc/msmtprc:ro
    - ${SQ1_PROJECT_ROOT}/dev/docker/wp-cli.yml:/application/wp-cli.yml
    - ${SQ1_PROJECT_ROOT}/dev/docker/composer:/application/.composer
  external_links:
    - "tribe-mysql:mysql"
    - "tribe-mail:mail"
  environment:
    - COMPOSER_ALLOW_SUPERUSER=1
    - COMPOSER_MEMORY_LIMIT=-1
    - COMPOSER_PROCESS_TIMEOUT=0
    - COMPOSER_HOME=/application/.composer
    - PHP_IDE_CONFIG=serverName=${SQ1_HOSTNAME:-square1.tribe}
    - DOMAIN_CURRENT_SITE=${SQ1_HOSTNAME:-square1.tribe}
    - DB_NAME=tribe_${SQ1_DB_NAME}
    - DB_USER=root
    - DB_PASSWORD=password
    - DB_HOST=mysql
    - DB_TABLE_PREFIX=tribe_
    - WP_DEBUG_LOG='php://stderr'
  <<: *proxynetwork
  <<: *internaldns

services:

  memcached:
    <<: *memcached
    <<: *proxynetwork

  php-fpm:
    <<: *php
    links:
      - memcached

  webserver:
    <<: *nginx
    <<: *proxynetwork
    links:
      - php-fpm:php
    environment:
      - VIRTUAL_HOST=${SQ1_HOSTNAME:-square1.tribe},*.${SQ1_HOSTNAME:-square1.tribe}


  ##################################################
  # Testing Containers
  ##################################################

  memcached-tests:
    <<: *memcached
    <<: *proxynetwork

  php-tests:
    <<: *php
    links:
      - memcached-tests:memcached
      - chrome
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - COMPOSER_MEMORY_LIMIT=-1
      - COMPOSER_PROCESS_TIMEOUT=0
      - COMPOSER_HOME=/application/.composer
      - PAGER=more
      - PHP_IDE_CONFIG=serverName=${SQ1_HOSTNAME_TESTS:-square1test.tribe}
      - DOMAIN_CURRENT_SITE=${SQ1_HOSTNAME_TESTS:-square1test.tribe}
      - DB_NAME=tribe_${SQ1_DB_NAME}_acceptance
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_HOST=mysql
      - DB_TABLE_PREFIX=tribe_
      - WP_DEBUG_LOG='php://stderr'
      - TRIBE_GLOMAR=false
      - DISABLE_OBJECT_CACHE=true

  webserver-tests:
    <<: *nginx
    <<: *proxynetwork
    links:
      - php-tests:php
    environment:
      - VIRTUAL_HOST=${SQ1_HOSTNAME_TESTS:-square1test.tribe},*.${SQ1_HOSTNAME_TESTS:-square1test.tribe}

  chrome:
    <<: *chrome
    <<: *proxynetwork
    <<: *internaldns

networks:
  proxy:
    external:
      name: ${SQ1_PROXY_NETWORK:-global_proxy}
