# SquareOne Global Docker Config
#
# These are default values for each of the constants bearing the same name
# within SquareOne. They may be overridden by exporting an environmental
# variable of the same name.
#
# Copy this file to ~/.config/squareone/squareone.yml to customize or place a squareone.yml file in
# your local project's root folder.
---

# Config directory
config-dir: "{{ env('HOME') }}/.config/squareone"

# Remote configurations
remote:
  docker-compose: "https://raw.githubusercontent.com/moderntribe/square1-global-docker/master/global/docker-compose.yml"
  squareone-yml: "https://raw.githubusercontent.com/moderntribe/square1-global-docker/master/config/squareone.yml"

# Docker
docker:
  config-dir: "{{'config-dir'}}/global"
  workdir: "/application/www"
  network: "global_proxy"
  mysql: "tribe-mysql:db"
  compose: "{{'docker.config-dir'}}/docker-compose.yml"
  compose-override: "{{'docker.config-dir'}}/docker-compose.override.yml"
  cert-ca: "tribeCA.pem"
  certs-folder: "{{'docker.config-dir'}}/certs"
  cert-expiry: 825
  phpmyadmin-port: 8080

# Local Docker
local-docker:
  # Files to look for to determine if this is a Square One local
  files:
    - "local-config-sample.json"
    - "build-process.php"
    - "squareone.yml"
  compose-override: "docker-compose.override.yml"
  # path to the composer cache directory (relative to the docker directory)
  composer-cache: "composer/cache"
  # path to the composer auth file (relative to the docker directory)
  composer-auth: "composer/auth.json"

# Global Command Options
options:
  project-path:
    name: "project-path"
    shortcut: "p"
    description: "Path to a SquareOne project"

# Automated Testing
tests:
  php-container: "php-tests"
